### ISSUE TITLE
LoadError with LinearAlgebra Package

### ISSUE THREAD

**Issue by karenacai** [tawheeler/AutomotiveDrivingModels.jl#16]
I am relatively new to Julia so I apologize if this is a trivial question. When I am trying to load the AutomotiveDrivingModels with the command "using AutomotiveDrivingModels", I am getting a LoadError where it says:

ArgumentError: Module LinearAlgebra not found in current path. Run 'Pkg.add("LinearAlgebra") to install the LinearAlgebra package.

Is there some LinearAlgebra package that is required to install this package? If so, is there a link that you can provide for me to install it?

**Comment by MaximeBouton** [comment]
This error should be fixed by running `Pkg.build("AutomotiveDrivingModels.jl")`
If restarting the build did not work you can try the following:
```
cd .julia/v0.6/Vec
git checkout 0_6
```

More explanations: the package [Vec.jl](https://github.com/sisl/Vec.jl) master branch supports julia 0.7 whereas this package only works on julia 0.6 (for now). There is a branch `0_6` in the Vec package that works with julia 0.6.

**Comment by karenacai** [comment]
Thanks so much! This fixed the issue.

**Comment by MaximeBouton** [comment]
Did `Pkg.build` work?

**Comment by karenacai** [comment]
Yes, it did! Thank you.
